apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  labels:
    name: airflow
spec:
  project: default
  source:
    repoURL: 'https://airflow.apache.org'
    chart: airflow
    targetRevision: 1.11.0
    helm:
      version: v3
      values: |
        executor: LocalKubernetesExecutor
        data:
          metadataSecretName: postgresql-connection-string-secret
        postgresql:
          enabled: false
        dags:
          gitSync:
            enabled: true
            repo: 'https://github.com/johnstonmatt/three-azure-create'
            credentialsSecret: airflow-git-credentials
            branch: main
            wait: 40
            subPath: dags
        enableBuiltInSecretEnvVars:
          AIRFLOW__CORE__FERNET_KEY: false
          AIRFLOW__WEBSERVER__SECRET_KEY: false
        fernetKeySecretName: airflow-fernet-key
        webserverSecretKeySecretName: airflow-webserver-key
        config:
          webserver:
            expose_config: 'True'
            instance_name: CNDI
            enable_proxy_fix: 'True'
            base_url: 'https://airflow.three-azure-create.coolnowdemoit.com'
          operators:
            default_owner: CNDI
        logs:
          persistence:
            enabled: true
            size: 15Gi
            storageClassName: rwm
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          jobAnnotations:
            argocd.argoproj.io/hook: Sync
          useHelmHooks: false
          applyCustomEnv: false
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 4m
