apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-public
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: ingress-nginx-public
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    chart: ingress-nginx
    helm:
      version: v3
      values: |
        tcp: {}
        controller:
          electionID: public-controller-leader
          ingressClassResource:
            enabled: 'true'
            name: public
            default: 'false'
            controllerValue: k8s.io/ingress-nginx-public
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-resource-group: nrg-cndi-three-azure-create
              service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
              service.beta.kubernetes.io/azure-load-balancer-health-probe-port: '10254'
          defaultBackend:
            nodeSelector.kubernetes.io/os: linux
          admissionWebhooks:
            patch:
              nodeSelector.kubernetes.io/os: linux
          rbac:
            create: 'false'
    targetRevision: 4.12.1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-public
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=false
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 4m
