---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-fernet-key
  namespace: airflow
spec:
  encryptedData:
    fernet-key: AgAbW3elaJbRF1rlh6hyGep9qsAEeHcmkXdfmwUK75Cni4jS2+W+EEtwoLpNlj6zE4cduqBat8wjYc4mtvEjCFy2hau3+4Q9MxXnYxXFyz6WMAbOrfgogLM/008TMFp0H9kyo/t3QPp0kRkFFIt6WD2bEyJX2S9z1hPwLEOnkqw6P/SbGlyQoDDSxnpCymTMRE14xB2qPqejZeQuvV70g0aVHNOn++Td8IhnpGNO8vSHIjGcofAUV/WaX6ycUoRkQM6PjdviwRM9aW488OvNOybrOQ3qgqQX0rzcDlr0I+t1JmGNKJtMus34u+Hv1SfnYaSk3adI3oU+bh2RbneVJaQbn4GyxSzdt/kd6gju+KPAjseKYpc/WmCcTRx1SL3pnB+WzJSsM+m+wQPgzUtOb4qjvYBrVGA/h21i1GRumiqH9vF9GYzmZF4Wb3gRv4gFZSWBzkvlsGOHttzLDhqV3vAW3buxRZxjr3UV9/ITlde94WqRgLZtO7q8CbttkFw/d5fVXRKNTBF3pTu8XHjuZHGUgBm7S301NZyhEkYvrKwHbRtANJxQaeNnL0N4DgIhGdLhUHs6u8Vw/dxL6c9IjMjou4axkDTyjTNRZLYJrjAVOmmgBA8EPS9CiKlQpkxc4Y4NqJyiOyrqKzaUXk66SvkH9I9cWTDgFZtpFD0MnT8IvIiYe1JHXWRDd/r34aDeAbwr20n2i/DO5fqPBiC8qYEkb/hPBryPYgwVZAqloYQgkQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-fernet-key
      namespace: airflow
    type: Opaque
