---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-webserver-key
  namespace: airflow
spec:
  encryptedData:
    webserver-key: AgAEoWfjHZbo3M4Ws5T9zriV67A/rui3uKCCEfWzyPBcrT5Lq2167ULobzNkBpV6oc41quyyFYLk0ZQ3Gh81NI/3GDsC2nYZU7f6daU3sBBTj/YJ+nLoShE3gGsFe3EcCSIOyxdv30d1nD7wv/QkaJbkDoxMvMZ012CCrlwX6F0V3aPkZWJ0gewwJEfQh2qQZfMx7eE8oNTA+YqVF4MFoeCvoS9BUEED0W51+deEBpuZrt0vuPrAW1rWz5LbYaOnIQuoAsLyxHxExk1NxjiXWtogEgjSvlM5FM5IoB3rCCWYBjGS9Fpi1/ecH0iQqBof9iFXLwvKMEYJBEOVPb5R6gxROEm1qiQ8S/tZsmtu8pzkt9ftftz0G3hmC4y2WUuw49zjt0+RjvjZRRq/LjWRWv4lLeEgyr7sLbtiN1Ui8+jWhmCrGsiOPPl3dnlrQ6AcBPZzJukWFtitV89b12AKkGvAWaJod9nDk/2Ld6mGpOERM2m/v5y0uk6wLUNEJlAETMhWPmJ63TaTY59v7CplUCLnUgrH+kVX/WVe8gmMJUMD95b3tG3wOZAQKfFwuTt1o/c1Jx8Q2t3ly2vtT0yRsbMMl8NMe/+wMNxbRZcE2o2WlSpo9pp7CffVQB+fzDjFMcb7+ljowKi1E/wftBF2qnG9b8QT+jQlqIZXGdLlesLRXFookk9zzJtCWaaNYBfAafpy8HJQ7MztGTLzBOay3I4c
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-webserver-key
      namespace: airflow
    type: Opaque
