apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  acme:
    email: matt.johnston@polyseam.io
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    privateKeySecretRef:
      name: cluster-issuer-private-key
    solvers:
      - http01:
          ingress:
            ingressClassName: public
