---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cnpg-cluster-superuser-auth-secret
  namespace: airflow
spec:
  encryptedData:
    password: AgCNuBvDVt1y7R1lkOfhOgWnbOf/rmhgjA/lkutzbX8m81966OKy9AeeRxsaA+D/DC0XeXCMVterNrCodF0kg/GknB15hIlBwIjeabSHO32KSqwtl19jFb1QVT92TWxsbMzlcN12JG8D8/r7iDwQ10oJks4zYIG9eTHZtH+klrd+cFSHumBk4wAhrVvWZb7raLtnV4mhkc+qTcQnYqiemBhyOeEgrY0h3fYfzpcohs87PZsf9lu5JogT/g0QJZfEL59F76vzWCvPxMyg6qjIQn+I5+Xba6jndKP9DYAc9Mma7IdtYnbDBpQQdxflec7NhwbPZpMcSYVntmlKAqi5Qyec1zKn955e2Nt9LBF+MJJlKz4LMtjntkqJ1tEeVtvDC9r4H2tQd7EKBDjLloEvjCqVG+P1pIZkGt1b6UetTTx1kuEBNl8WAdU8K0ZVdLaFOx/yIAGPmjZFSkZU4NTGCkYK8xVivrNdAPvdcrhYe6Ott/mD5IPL5hvq/pWlnXeEXwlZB8WZM/gKM9mzw07qa3SfU7ohzKD+OD3Q8WlYKjYYu6SsFYapsASYCIgcWk/FlnQCcRg8qWkY8NXVy4S+NIFqXEB2OZqoHOVEL8Oq1Jy22YCVid/IqZRzaEE4qH5VnQWPX1k+SN5FICTqv1VUWfxXo2Y+ui5hMdRh+BGjAfL54F3XhHtOvN0LtqLjGi7nVIM8fpyLt06HIcp1M+UFiLELfSnHyhFGrl4=
    username: AgBLt2OsUj1LzcCYHZ04JPh+ZUvMdZaXTrLW95aEGOnJlNxDgZi1QUFlsWWw6lCLXWSPL7Wtk05HQqEuu4sJ/ZB6ULbnxJolqxn/eYqgbNGFlI4KJAugYUWL6cmFyB69pk0u6p6GocDnecn1XB9r3wgyEi9GC/OIznlWpdoToTItIvB/X2y2pe3Go87s696FiwBbVnMXiEN5dqddjMt7+DX8+0pFIVZDqbkm1gjLKx2hExHdQFrQUq6+3ueOH6659vk610jLSKs39CK7jYQs/nr71NZh7lwgv2UxMr4SeiCF7naRkj5TiWfGF8lDmhaXJcO83xilm1UX5th7xS/7YFpUBX1MS6KxMcuKfLn7v3z0HYOQque+GyCnfC7UZ5bdQfTjKCLRPka8gNNFvx5WnR2bV3jrdhMgFkTAhi69TavLo2Se6z9uxJIRE53RRZlZHaXB7jnId9u6AY85H/njTO2RSRItnQPVxodpJGGf6HvjEbP9ob3PBH3HKqhblPbl3W9AHgKrjliis18mZ0rbTUrN8dKvJRodSgwDUIzjHowMa3HBFqx08EmouK76R+W7W0scsbE+A/uhdfAXfSreSMKLz9268+84CCPARCbavZMYaSPxJkcb8eYu4viFYdCHKQIarTEzjHHVciNRKYY9JY5YWw8lFCHgFsAaDuZw0xT4AnKjX5tB7KrITZf5yCGzO4oUelqi1TkOXw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cnpg-cluster-superuser-auth-secret
      namespace: airflow
    type: kubernetes.io/basic-auth
