---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cnpg-database-user-auth-secret
  namespace: airflow
spec:
  encryptedData:
    password: AgBmIHAnByFaGadrjNXdzI6PsaqXOgZ9jruwAq76GLAH7ERcg+oQfc3dQZZxh7CQhDoezWwxQ5ywphNx2UuTzPvuUHOZO4DvmWbRoUqIW2TgZ0z4h2Z0SeRBQl+aeEgSqa1QgQKTkjucMfVqC8x+ntn3SL5acNvIOXOh8GwJQaqawI4DREtvDgpfwC3efPgbiVd3lxyKyIO2bkOyO8HShAwo0QgxFpSI6/kCXOqEv4OQgH0uk4+TDToYtYv6CBESnnl8PyJwtg8z0vXwyQjtB9zEvaF1/yy2YFPAIrIP02rydbPXuqXEbUtlMbSfYg1eaBiuyIZ/2EGa2oOFDWT18thW9p1ozmsPNYh6IAaLzKHV9+6b0lbHrVPg0DRyiIhi6aU8SBBrxPKmzKd94ChyvGTQyoAz3BuxKGjoXMwyn76FdTP7JYaMxj3GoFcI0pBtC8ObGcXyLaMZ4fXDnM7Rr4mXBZKprfBHMeTyvMB3A3kLt2V5R5LfYin3kmH1jsW5oIqFSQseUGccdqQuOoiYwc6/EpyHRyYGtfuz6fuInd7vlzO672f5bHo8rM5cRbCEfY2d0LiXbsvkE6faSNPRNjVaoTknMCR8bUNE9O0bWntIT9FOpnj0si++eFEsGseCYMfY9/ISQmMHCnsW8wvnzgjkP7vrAo2OCs0hTjkV4KeQf+Nwp4O9+V9g2Q2ZqnlTgicll87oHRtZzv6ERzU=
    username: AgBgGZFeHfhKG8kcy9GRIWvTS/ZKK54fQjnVKcPJ5alhL/5L51oDfxDVgLOoDlHf9CmBH6x4Z6B/tQpGBjfm29ru64sk7+jrSAi5lt7XAGlufOYkTXleq3deGZVDkiul6ZPG+H3PEJJSg5RGh3AyRp0gIE4nDu/1Ih242UhrF/g3oNmfLGBLJhkqi99EETwVqh4CImU11QQBggf0vekefT86X/kNAI0yFSIuHuc7tm5TU41qDnGtbWhKXn0DQk6TZAOhl0JPvFmNd69UtVW6pMZTifO9AUQooMRyhKbyoQVrnZmV1LdsXpSUEJ6e/KrOtXUaGzE1Eb8D3UbSlS4ZiALt4UmZE31dQi4cENI4hUOLjanJY4l3sK37ecm/+IM1jtM5DH8AHJJgUYV+Uyl+/AhjPjZzi/ineKITQQ8ON6dcWGd2+1i/WD7/MGWesdkUQUzEqLbeiNtEvWKI0d5F5Xh6TWCmUXJ8FS4lNesNEnB2DwbiVgA80Gy29NkQwwJMGxYCD+AQtKEBUE1kyc+PaeQ5tTioCyiPYX5FzQMdkv75ybgxJOveIGz2URdn8XhEfck7KQOpKIIdREdBwtw39HmQFN/9J1tZ89yNiFnpYjrf2lD4UfTzG4QPTFlHnST8lA/UgX91EOfiGdwURmP80+ev9yN95CM20SB6FiPDbRuBPOGP8U4XIJIYWBRZRQKmypB+iXrpEdN6
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cnpg-database-user-auth-secret
      namespace: airflow
    type: kubernetes.io/basic-auth
