---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    azure.json: AgA4x3K133f3d0zAxDUjnobBMMAhYwCDRXYyhEl9oqu1KlpJfSu0KAzOttWmVy+CGdDZtoqc4CaqQqMPdd1YY+Y8OGL7HzdI9SBBLfGyXcrwO/yNQNCa15EmWtOHvtW7YJ2aIG5VcXPWHE8+ZeARbEnJ0aErM/6T64tm5Y899Tm+HN5mCMqgOoyIeqkadyoKP0tDuD20oaDuD+vV9SirPUs9T7GkzPQ37JvMkRqkNg0669iXb8U5RWqWTA4ybDULcduOLfzIUSNiySLWpkR52uxDeimEScc0MHMmw7EzNpIUNAQPFXokSLx4sOOwxeI79eaN4mOfXAEtEBUf6HnYVb8rlWWq/0dFe3HavRdm4jJZavcOz/RUKo/+dlQ5m4B+yBx5WuONJo1g1Vb0FmEVJ1zFu8eNkC2NUr5cqBZ8twb0hkGgMe2CkBPVUUA0nqoexaTyYXhE9gt06fixSrxPcJqBjKmDqIpZA4NglQ1CvayzcFqyz8O0CJhYbpTqwgdEbfz7ku5Uo5tIam1GAc9QUosZF+VAho596zhpkzWXctlalBrjO4fYY3PXACejYzy+Nq212J7w0WyB/eZgCSUCKwQYTNhSPVybbfTb67ewOHoggALfk7ZJXBGgBQhQJDASxA+P7Q+VQ/YhdgX83j3OdL2Bnp2nBuA2lCYmTLmmfXwE9FIf1HX7sgPgwTDyOBUX27FhQL0XeXqPXzHsVhJo+FvH7u5uCDO7nR7ylpEo+DCVLdcwTG+CmiujgF3ZEaC9BC7wOIyrEcbc2M+bDnuv9S9oqH3EWVSLc7FPVJy9Z1sgAo2aU9wQiTX9Xsn98JFwPRykhUMDtCIsLWlC0uufWOQs7QzZNYekIMGvMlvPqk0bvUrz6ubDR6BKNVrkH2d3R54yDIMN2CUncViG8fFputPTrAc/7FrURMfwk9V4x4gbyY+ArYxu+rq28Xt+Jr301uKfnKs+hYkaYJ/VZVT04EiXkzJJWP2kBAMEYLMv/fmsVcJ9UF8PsD2cPTRMZV+6vvcjcuvxiRx3qcMzBOVFrbN+6zDDaWKBKhyo3Q92svJRXDwwhA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
