---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    azure.json: AgAdaW7NO4rZooRDooBomhSjDSYxDDXY82jGcQNwQVdTxcPwy5cr1BxCw69m5x1KDvoi6rliJdvN9guV2Tx5ABUROQdvdDiGiVSQ+7QtFs4f4a4LcjDwaEl6TWFJPveare5wJfD5ieb66SuDTvCCKTH0vVx3cr7xP+OlFt8SujBsCH/+suIYWyFnWubNK+jdiVR0YNEv+c5AN67dDs7nczsLdlxtF5Dxj7gBr64kW5EUwjr3ib68WxEX5uV0QmGP67DSwUxtDLg1kS7rO1j1BJX3cOAGvkc2cSYy5nyze8b9NEfPqn3tjkrnrWdamFo8Ypxa+b3VzszPKz7vy5EZpEBMAh05iXlMJVDvy4YqClwV2PQkebzCcMSWyh9vdhLpMosqFrxyLcgqp13ACB1A565BxS1TRrpYhotQU/9rXdR5f4yfNdUEjMvhr35/t+np+aX2yYEMFExKxopB1jnDNpo/jnIftK71fWbcoo5vV+Twqzz4wEuxRE3NmX70qjQL1wFWYY0ot0DQbAAANe1hqFJ2n50SB3E9ANQ3aDpEwzKTrCH4EFzRT7QhevYyZIxJjEvbtkN/Bg/MCiBpjT76NniUO6vmVzBVN0gg5Hwlck7kyQsKNdbCLCs3JY+uX6GnvAFvngWsAEh6C5A45khZkTRlYWIcWVXdzgkuBqHSxDFu0lt9dqOcOKxwnaNwFfx/VbQoZlk/+DyYE5Y7psXJFJBklKAOgTi4rXJuBO3AcGsTuNxw7vdcTmAULcDMxZF5JJ/Y10QmnNdwM5gBWTVzYiOkQkDOlEcOGT7gDIFg6Weu/L6neI/Otvj52Ilep3uFJCoSIssm0LE7waLwhN19mldIPU2DtL6uIWBiRB63/zuxGNAXj+fe2YvfcHToa/1C206gr/vre71JprK1RwpmTZU/mdjUxYfy9UBpk69ZX5Tlz3PnH2GJEQwO3U/wTxzaOJNV+Sao1ewt/Wsqzs2vss70w5qaGUSIkFtvT1Gl6BV5qtlyZDcHGv/NC2HiP7FCPnU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
