---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: airflow-git-credentials
  namespace: airflow
spec:
  encryptedData:
    GIT_SYNC_PASSWORD: AgAzieNprow85NpCIXyIvByKZ/SY2yPng0fYQpUPFA4vbcTALv0qcfrH9RwigWqXr4W3xYUKKmKpbQHGJZchEXx9Ml2ZnlYwKgPbSqbEa+/JaSyvCQ7VXnGkggkjPDXszyXhbBdoWss935Pw5wrirAo5bN4abLtkwNciyKB9fEOYKP4/yO8yxrKo9+YPwe4TRe6l2aIAC/7nN2r/TzDYVyNXSlhSeDeRa/NzD0evI76m07eL68JYOFR8DJZy+fml9TnNnm3aurIzS+2NZPBYAd3R8PrX9OvS6majf+YeVzYPyCLanidR7GMVuMoDg7iTMcQqVp9UD7Ak01kTjiQYOGcnwsZ6ndoWVG20+xgvoUItnmhn8+0TiI0wZvLKrgbyZJnCAmP/fXr8+HYhI50nF6Jth4a+TuJcoW9sP6Y2Cu72dmpWuX/zzwi0qPXQcpLUAER8mJTba5bI95TmCWXVBB0h/w8SElXMMw6s1vz51KopmjFpYJGSt83ujGEnsXX4mH272xK2V5v+JixoQ07caHcitES70UYGEee/kyfjSWetTfOevWIMVEk5imrWcAHP/wjm9zZbcxPtvGEDIa5yvHhsvcIApItZObLAMCyFAWrShmrq1gitTakNVkeig941m3oA0278m8b+yHrRR17CztqxiGDJ3/aqqVZ1H2ABRD/3aVCquuc0SUJhXgafp8IJQS1XWpCNjO4oulToKN909F17f+bMYTQ9QezbV9VnYNFjU+6vUHwitLor
    GIT_SYNC_USERNAME: AgAzma59x/0crt4OUAzr+bCD4XwydSQPODbeuZHHzOppMB5h+JJLDrpHe596d+RsYAzl2iPuFWbZfgdO8tRjn1WdXPuYltYp4JK8jtQdYcRxUciegvu+fZweeFnWlDOH90U+8j35fX2V1ckUd0++cqHw+Meg7vbcjaK0phc1Ix3IJHHkR5xatRhixqMyyOZt9YGh+Q420BgCK4RDYHLvSLS3WMX+TEN91mbc8GzxWBrOOsuSlh3J2wC8+889nsMXuwA2UXXNwaVvh/PGkeqQgdWv13nBQI63st0t0MNNQSDUoBMx41uUXvO6dKvJ4P9lb3rvXZk32GO1wpbMrx+eABsihjSciQeUJ7VVdzP7QOzxa4FupkSyYenfPXS6JFFQlha1fHgb6Z5F0m3h8gY7xaLL2J+8INkOVot3uY8r9oypNWy7YjIS2gI5/fJtHruq04Lm1yvD6jnLmwG2jCPWxHl7lRNsjn+JeL8SVtL23P9Si5lnP6BrmzU3Rs5s/pDf5W7A+Nc7mL4meA9TK/FxYua94Oe9NwnhED+efFtpHasSsyrvnbusrszafzmEBMBO0R+3nuOtfw/dqGa7bKLhzjLxgZPTyEGR7ag/Xypa+VXFReFqUkGvN8yD4nCP1GGBjMYMU5jtevrTLaomPvldOzK7W9DwYEwfrnDZ6c6zP7MHFFiPzNW9kh2lRqAclZbj8QbZK48bh3cRY0ZO26s=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: airflow-git-credentials
      namespace: airflow
