---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: postgresql-connection-string-secret
  namespace: airflow
spec:
  encryptedData:
    connection: AgA6LfNFvGI1Vfv/Wt9kOYv4Gyh5vwALai6RPd/sPztgFNoYVpLN1brFzK3yomeK+cHx2qMgDCXfRPR1Pe/D7Ot3Pu+eTlNfwhM1xzK3hORyYzrUwg2saBzYeoqUN+iMS5Db9UyTG/qPlhNKIs2M7/TnhTQalsf8J/ROT8dhBJL/E9eGhafkQtd3iUV0orDQvTpJkIZ9dMqgqsI2O6mc63tIV+MEc/MYJb8yYRPu2Kr+fIiT4Iim0PIw/d0krh/KRW6BhGN0XsRH15flcp8ZgR4sU0b399+daSHfBp1QcrPgtXqFOkSd60P1o0NYCBBtPvr6wZ2QZY/T/K6OL2hAVWikkldiIvKOeV+Tg6DqszFCZKMFUBjh8DzggCilZllT/BWHE2iiuIZI2A3Dwf8JBX1HXD3TVqk+DhyzLf0fqCejCQu1nD93K+4jSdZg4571qSBX6DthRI2siU4q7ffxdMvrqOdh3ZX6cF+vZlg05GYGE9BwckWAIzNG9er3T+SPTalx/icooiODWlv2rhMrEU4BTyvB+uIn8y+uHRtxNj+eq00w7Xh7AenJpZ5vNxU9y1wA9SheR3fI5PMa+OvAeZm/3Is76PixziLr+YBCC7G7KxZ2jskY+3Mxy3j6B9bfLtfxH8tdJrRXIQXrUhhDi51O7gz2dNtjXK1jHaCNoOzFOpYdJwSvbKdYmRektY7sEMPu/00uF4wWvJkCGqogy4g76iBEtI2gS/HSRiBrtlHyV7kNTFKROet0h9exk8ZOiT7OcdFdwXDYdAnt3wWgbQ/HhVbWA92XpiAk
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: postgresql-connection-string-secret
      namespace: airflow
    type: Opaque
