name: cndi
'on':
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  cndi-onpull:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GIT_REPO: '${{ secrets.GIT_REPO }}'
      CNDI_TELEMETRY: '${{ secrets.CNDI_TELEMETRY }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true
        with:
          directory: ./cndi
          output_format: github_failed_only
          output_file_path: 'console,checkov'
          skip_check: 'CKV_SECRET_6,CKV_SECRET_3,CKV_AWS_341,CKV_AWS_184,CKV_GCP_26,CKV_GCP_65,CKV_GCP_66,CKV_GCP_13,CKV_GCP_69,CKV_GCP_20,CKV_GCP_25,CKV_AZURE_4,CKV_AZURE_117,CKV_AZURE_170,CKV_AZURE_116,CKV_AZURE_6,CKV2_AZURE_31,CKV_AZURE_115,CKV_AZURE_141,CKV_AZURE_226,CKV_AZURE_5,CKV_AZURE_227,CKV_AZURE_232'
      - name: Check if Checkov Results are Empty
        id: check_empty_results
        run: |-
          RESULTS='${{ steps.checkov.outputs.results }}'
                    # Using grep to find any character not in the set of '-' or whitespace
                    if echo "$RESULTS" | grep -Eq '[^-s]'; then
                      echo "empty_results=false" >> $GITHUB_OUTPUT
                    else
                      echo "empty_results=true" >> $GITHUB_OUTPUT
                    fi
              
        shell: bash
      - name: Comment Checkov Issues
        if: '${{ steps.check_empty_results.outputs.empty_results == ''false'' }}'
        uses: thollander/actions-comment-pull-request@v2
        with:
          mode: recreate
          comment_tag: checkov-failures-comment
          message: |-
            ## Checkov Failures
                      
            Checkov found issues in your pull request. Please review and fix them.

            ${{ steps.checkov.outputs.results }}
      - name: Delete Comment Checkov
        if: '${{ steps.check_empty_results.outputs.empty_results == ''true'' }}'
        uses: thollander/actions-comment-pull-request@v2
        with:
          mode: delete
          comment_tag: checkov-failures-comment
          message: Checkov found no issues
      - name: Print Checkov Results
        if: '${{ steps.check_empty_results.outputs.empty_results == ''true'' }}'
        run: echo "Checkov found no issues"
