name: cndi
'on':
  push:
    branches:
      - main
      - releases/**
jobs:
  cndi-run:
    permissions: write-all
    runs-on: ubuntu-latest
    env:
      GIT_REPO: '${{ secrets.GIT_REPO }}'
      CNDI_TELEMETRY: '${{ secrets.CNDI_TELEMETRY }}'
    steps:
      - name: welcome
        run: echo "welcome to cndi!"
      - id: lock-check
        uses: github/lock@v2.0.1
        with:
          mode: check
          environment: global
      - name: fail if locked
        if: '${{ steps.lock-check.outputs.locked != ''false'' }}'
        run: 'echo "cndi cannot ''run'': deployment in progress" && exit 1'
      - id: lock-acquire
        uses: github/lock@v2.0.1
        with:
          mode: lock
          environment: global
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup cndi
        uses: polyseam/setup-cndi@v2
      - name: cndi run
        run: cndi run
        env:
          GIT_USERNAME: '${{ secrets.GIT_USERNAME }}'
          GIT_TOKEN: '${{ secrets.GIT_TOKEN }}'
          GIT_SSH_PRIVATE_KEY: '${{ secrets.GIT_SSH_PRIVATE_KEY }}'
          SSH_PUBLIC_KEY: '${{ secrets.SSH_PUBLIC_KEY }}'
          TERRAFORM_STATE_PASSPHRASE: '${{ secrets.TERRAFORM_STATE_PASSPHRASE }}'
          SEALED_SECRETS_PRIVATE_KEY: '${{ secrets.SEALED_SECRETS_PRIVATE_KEY }}'
          SEALED_SECRETS_PUBLIC_KEY: '${{ secrets.SEALED_SECRETS_PUBLIC_KEY }}'
          ARGOCD_ADMIN_PASSWORD: '${{ secrets.ARGOCD_ADMIN_PASSWORD }}'
          ARM_REGION: '${{ vars.ARM_REGION }}'
          ARM_SUBSCRIPTION_ID: '${{ secrets.ARM_SUBSCRIPTION_ID }}'
          ARM_TENANT_ID: '${{ secrets.ARM_TENANT_ID }}'
          ARM_CLIENT_ID: '${{ secrets.ARM_CLIENT_ID }}'
          ARM_CLIENT_SECRET: '${{ secrets.ARM_CLIENT_SECRET }}'
      - id: lock-release
        uses: github/lock@v2.0.1
        if: always()
        with:
          mode: unlock
          environment: global
